project:
  type: website

website:
  title: "Degrees of Freedom Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ChemE.qmd
      - Rocketry.qmd
      - href: samples.qmd
        text: Samples


format:
  html:
    theme: style.scss
    css: styles.css
    toc: true

execute:
  freeze: auto